# Generated by Django 5.2.4 on 2025-08-05 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datetime_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('calories', models.PositiveIntegerField()),
                ('protein', models.PositiveIntegerField()),
                ('carbs', models.PositiveIntegerField()),
                ('fat', models.PositiveIntegerField()),
                ('image_url', models.URLField(blank=True)),
                ('time_logged', models.DateTimeField(auto_now_add=True)),
                ('parent_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='datetime_app.day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodlogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
