# Generated by Django 5.2.4 on 2025-08-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='image_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
