# Generated by Django 5.2.4 on 2025-08-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_data_app', '0002_alter_foodlog_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='image_credit_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='image_credit_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='image_credit_source',
            field=models.CharField(blank=True, default='Unsplash', max_length=50),
        ),
    ]
