# Generated by Django 5.2.4 on 2025-08-05 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(unique=True)),
                ('weekly_calorie_total', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('daily_calorie_total', models.PositiveIntegerField(default=0)),
                ('parent_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='datetime_app.week')),
            ],
        ),
    ]
