# Generated by Django 5.2.4 on 2025-08-05 18:21

import django.core.validators
import user_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, null=True, validators=[user_app.validators.validate_name_format, django.core.validators.MaxLengthValidator(20), django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, null=True, validators=[user_app.validators.validate_name_format, django.core.validators.MaxLengthValidator(30), django.core.validators.MinLengthValidator(2)]),
        ),
    ]
